name: Deploy with Password

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Backend with Password
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          ssh -o StrictHostKeyChecking=no skfnxh@rgpsh.iptime.org << 'EOF'
            cd Z:\workspace
            git pull origin main
            docker-compose up -d --build next-demo
          EOF
