name: Deploy Next.js Frontend

on:
  push:
    branches:
      - master

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Frontend with Password
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -t -o StrictHostKeyChecking=no skfnx@rgpsh.iptime.org << 'EOF'
            cd /d Z:\workspace\next-demo
            git pull origin master
            npm ci
            npm run build

            cd /d Z:\workspace
            docker-compose up -d --build frontend
          EOF
